In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-06-27 16:23:46.224314: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
### sentence
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
### Define vocabulary size
voc_size = 10000

In [4]:
### One hot representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1517, 9688, 3700, 4646],
 [1517, 9688, 3700, 9439],
 [1517, 5011, 3700, 9965],
 [5379, 1882, 8080, 467, 3661],
 [5379, 1882, 8080, 467, 6541],
 [996, 1517, 2090, 3700, 1933],
 [4038, 9458, 8454, 467]]

In [5]:
### word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen = sent_length)
print(embedding_docs)

[[   0    0    0    0 1517 9688 3700 4646]
 [   0    0    0    0 1517 9688 3700 9439]
 [   0    0    0    0 1517 5011 3700 9965]
 [   0    0    0 5379 1882 8080  467 3661]
 [   0    0    0 5379 1882 8080  467 6541]
 [   0    0    0  996 1517 2090 3700 1933]
 [   0    0    0    0 4038 9458 8454  467]]


In [8]:
# feature representaion
dim = 10

In [9]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length, input_shape = (sent_length,)))
model.compile('adam', 'mse')

/Users/syedsaifullahtarique/Desktop/work/Udemy/Udemy_projects/Krish_naik_genai_with_langchain_huggingface/ANN_project/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
/Users/syedsaifullahtarique/Desktop/work/Udemy/Udemy_projects/Krish_naik_genai_with_langchain_huggingface/ANN_project/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[ 3.43255438e-02,  2.93012895e-02,  3.12201120e-02,
          4.20634858e-02, -1.41408294e-03, -4.34256457e-02,
         -6.47096708e-03, -1.55588165e-02,  1.34760141e-03,
          4.09247726e-03],
        [ 3.43255438e-02,  2.93012895e-02,  3.12201120e-02,
          4.20634858e-02, -1.41408294e-03, -4.34256457e-02,
         -6.47096708e-03, -1.55588165e-02,  1.34760141e-03,
          4.09247726e-03],
        [ 3.43255438e-02,  2.93012895e-02,  3.12201120e-02,
          4.20634858e-02, -1.41408294e-03, -4.34256457e-02,
         -6.47096708e-03, -1.55588165e-02,  1.34760141e-03,
          4.09247726e-03],
        [ 3.43255438e-02,  2.93012895e-02,  3.12201120e-02,
          4.20634858e-02, -1.41408294e-03, -4.34256457e-02,
         -6.47096708e-03, -1.55588165e-02,  1.34760141e-03,
          4.09247726e-03],
        [-2.81281956e-02,  1.99261792e-02,  4.86132540e-02,
          1.76980607e-02,  1.75827779e-02, -4.08532470e-03,
         -3.94652970e-02, -2.15317495e-02, -3.786323

In [12]:
embedding_docs[0]

array([   0,    0,    0,    0, 1517, 9688, 3700, 4646], dtype=int32)